// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuyRf1QbWX7bN_FUuaCjCRAW2vW6-6XQ',
    appId: '1:414048783310:web:73c3fbb37a0725ce98f99f',
    messagingSenderId: '414048783310',
    projectId: 'newshub-e0ec7',
    authDomain: 'newshub-e0ec7.firebaseapp.com',
    databaseURL: 'https://newshub-e0ec7-default-rtdb.firebaseio.com',
    storageBucket: 'newshub-e0ec7.appspot.com',
    measurementId: 'G-DH0MVBPNFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASjdT6jAQYEXd2RhM0acwtwB3ErQUNG9c',
    appId: '1:414048783310:android:e7420935b70626ff98f99f',
    messagingSenderId: '414048783310',
    projectId: 'newshub-e0ec7',
    databaseURL: 'https://newshub-e0ec7-default-rtdb.firebaseio.com',
    storageBucket: 'newshub-e0ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnv7201FToYuOtAa9tSiBsG1bhDDmszwc',
    appId: '1:414048783310:ios:9705e5cc33f70d4b98f99f',
    messagingSenderId: '414048783310',
    projectId: 'newshub-e0ec7',
    databaseURL: 'https://newshub-e0ec7-default-rtdb.firebaseio.com',
    storageBucket: 'newshub-e0ec7.appspot.com',
    iosBundleId: 'com.example.newsHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnv7201FToYuOtAa9tSiBsG1bhDDmszwc',
    appId: '1:414048783310:ios:9705e5cc33f70d4b98f99f',
    messagingSenderId: '414048783310',
    projectId: 'newshub-e0ec7',
    databaseURL: 'https://newshub-e0ec7-default-rtdb.firebaseio.com',
    storageBucket: 'newshub-e0ec7.appspot.com',
    iosBundleId: 'com.example.newsHubApp',
  );
}
